### PR TITLE
Proposal: Openstack 

### PR DESCRIPTION
**Pull request by GeetikaBatra**
I have initiated a presentation and the work is still in progress. 

---

- [x] Link to presentation -> [here](https://docs.google.com/presentation/d/1vEOhqBLpqVXEoAQkgAFc0xim7myHLnZpFh_7lv567as/edit?usp=sharing)
- [x] Date finalisation (22nd August)

### CODE REVIEW

**Comment by satyaakam** [comment]
@GeetikaBatra pick one small piece of the problem you are working for the project and talk about in context of the big picture how it works in the Openstack ecosystem overall.

**Comment by GeetikaBatra** [comment]
@satyaakam  Sure +1:

**Comment by amitt001** [comment]
:+1:

**Comment by ajoyoommen** [comment]
+1

**Comment by CuriousLearner** [comment]
+1

**Comment by satyaakam** [comment]
Saw the initial presentation , its still not there , lets talk about it more in IRC , i have some ideas for it .

1) i do not see the python connect anywhere
2) too much of theory 
3) Since JNU is looking for setting up a Openstack lab may be this is your opportunity to impress them with a Workshop or Codesprint and fix few bugs 
4) We have still two weeks to go do you think you can pull this one ....

**Comment by theskumar** [comment]
@GeetikaBatra would be possible for to arrange and update the PR with slides which Sajid gave or it is fine we just add your slides to this repo.

**Comment by GeetikaBatra** [comment]
theskumar  I will ask Sajid and Syed for the presentations and will soon update the PR.

**Comment by satyaakam** [comment]
@theskumar  Generally they post there slides here http://www.slideshare.net/openstackindia/ , if it is still not there we can ask Sajid for slides.

**Pull request closed without merging**
