### PR TITLE
Proposal: How to handle asynchronous task using celery

### PR DESCRIPTION
**Pull request by KdJohar**
I would like to give a talk upon how to handle asynchronous task using celery on 8th of august

- [ ] presentation/content links
- [ ] date finalisation

### CODE REVIEW

**Comment by CuriousLearner** [comment]
+1

**Comment by ajoyoommen** [comment]
+1

**Comment by amitt001** [comment]
:+1:

**Comment by akarambir** [comment]
+1
@KdJohar  It seems your talk is on the milestone for 22nd August, please confirm that you are available. Presentation is one of the essential requirement for talk selection. Please upload a link to presentation on/before this Saturday.

**Comment by theskumar** [comment]
Closing this as we are not getting any response from proposer. Please re-open as appropriate.

**Pull request closed without merging**
