### PR TITLE
[WIP] changes to frontend

### PR DESCRIPTION
**Pull request by yellowwoods12**
The original UI of the website was very dull and simple.So I customized the original page with a css-customized navbar, added a background image with the talks and pydelhi banner so that the website looks presentable and unique.

### CODE REVIEW

**Comment by triptishukla** [comment]
https://triptishukla.github.io/talks/
@rajataaron You can check it here.

**Comment by triptishukla** [comment]
@rajataaron @aaqaishtyaq I've made some major changes to the PR.You can review it now.

**Comment by CuriousLearner** [comment]
Why are these changes needed?

**Comment by triptishukla** [comment]
Because the current website is too dull and does not look good.So I improved the UI and added the links to various pages.

**Comment by rajataaron** [comment]
Hi @triptishukla sorry for replying late. But the idea is to make a minimalistic website that's why we didn't change its UI. We need advice here @theskumar can you help us here?

**Comment by rajataaron** [comment]
@triptishukla I respect your dedication towards work. But I can assign you one thing. If you can please make a contribution section in the existing template that would be great and much needed right now.

**Comment by realslimshanky** [comment]
Any updates @yellowwoods12? Are you still working on the PR?

**Pull request closed without merging**
