### PR TITLE
Added link for scipy session

### PR DESCRIPTION
**Pull request by shagunsodhani**
While searching for the video of that session, I found that the presentation itself does not exist on the website. So I added whatever material I had with me from the presentation. Someone add the video as well.

### CODE REVIEW

**Comment by theskumar** [comment]
Thank you the details @shagunsodhani. I think the good place for this PR is https://github.com/pydelhi/workshops/ . Let me know if you are able to move it there. 

There is not much there right now. But it would be great to have things moving there as well. The idea to collect all the workshop materials in that repo, sorted by topic, instead of author/date.

**Comment by theskumar** [comment]
The corresponding issue is https://github.com/pydelhi/workshops/issues/2

**Comment by shagunsodhani** [comment]
I will open a PR for adding link to workshop repo as well. But imo this should be present here as well along with other presentations.

**Comment by theskumar** [comment]
We don't record videos of workshops. The talks present here get displayed at https://pydelhi.org/talks/

That said, we can add a link to the workshop repo to the top of REAMDE, so that we don't duplicate data and keep things simple.

**Comment by shagunsodhani** [comment]
Ohh seems like I am confusing between workshops and talks. How are they differentiated?

**Comment by theskumar** [comment]
Workshops are hand on session where people sit down and code together for 2 hours. Talk is more of a one man show that wraps in 30mins.

**Comment by theskumar** [comment]
A workshop can be multi day.

**Comment by shagunsodhani** [comment]
Oh got the difference now. So moving this PR to workshop repo.

**Comment by shagunsodhani** [comment]
@theskumar I have opened the PR on workshop repo as well.

**Pull request closed without merging**
